spring:
  application:
    name: quantity-authentication
  profiles:
    active: dev

server:
  port: 8082
  servlet:
    contextPath: /quantity-authentication

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
