spring:
  application:
    name: quantity-search
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    contextPath: /quantity-search

nacos:
  config:
    server-addr: 192.168.31.79:8848

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
